// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package database

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Command struct {
	ID        pgtype.UUID
	Command   string
	Message   string
	Target    string
	Args      []string
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type Schedule struct {
	ID          pgtype.UUID
	Episode     int32
	Title       string
	Guest       []string
	Description string
	RunningTime pgtype.Timestamptz
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}
